---
- name: Set up KVM platform
  include_tasks: install.yml
  loop: "{{ virtual_machines }}"
  loop_control:
    loop_var: vm


- name: Configure Virtual Machines
  include_tasks: vm.yml
  loop: "{{ virtual_machines }}"
  loop_control:
    loop_var: vm
